server:
  port: 8100

spring:
  application:
    name: ZuulGateway

zuul:
  routes:
    coupon-service:
      url: http://localhost:9001

    admin-service:
      url: http://localhost:9005

    user-service:
      url: http://localhost:9003
